### ISSUE TITLE
Templates

### ISSUE THREAD

**Issue by sbhornjr** [saifshaikh48/SwDev_A1_part2#2]
Hey guys, I was looking at your code and saw that you used templates to make the Array class generic. I wish that this could be the way to do it, but unfortunately, CwC does not allow the use of templates. You will have to change the class (and tests) so that it only takes in Objects, and then create wrapper classes for each of the four data types (string, float, int, bool) that inherit from the object class. If there's a better way to do it that is compliant with CwC, let me know because that would be great. Thanks.

**Comment by sbhornjr** [comment]
We used the string class here:
https://piazza.com/class/k51bluky59n2jr?cid=330 (Thomas' spec at the bottom seems like the best), and the other ones should probably be similar.

**Comment by sbhornjr** [comment]
Don't know if you guys saw this, but on Piazza Prof. Vitek seemed to imply that the better way of doing it is to make a different type of array for each data type (so 4 different array classes I guess) (here: https://piazza.com/class/k51bluky59n2jr?cid=331).

**Comment by saifshaikh48** [comment]
Thanks, we’ll be looking in to this later today just to give you an idea timeline wise.

**Comment by xiaju** [comment]
As someone else assigned to use this interface, I agree that we can't use templates. Looking at the thread, primitive type wrappers or method overloading might also be ways to go here though. Whatever way you go, it would be nice to get the new API quickly so there's time to implement things.

**Comment by sbhornjr** [comment]
Hey xiaju, don't know if you get auto updates or anything but just wanted to make sure you know that they updated the API.
