### ISSUE TITLE
Small Issues

### ISSUE THREAD

**Issue by sbhornjr** [saifshaikh48/SwDev_A1_part2#3]
- For the push_back function for the BoolArray, its parameter is an int instead of a bool. Same thing for add, get, index_of, and set (returns an int and takes in an int) all in BoolArray.

- In your tests, when you run get() on a StringArray, you expect it to return a char*, but in the spec you have it returning a String*. I assume you meant to do char*, as the StringArray takes in char* at every opportunity, so you should change the signature of StringArray's get() to return a char* instead of a String*.

- For each test, when you test if Arrays are equal to each other, you test that s.equal() == u.equal(), which is not correct. You should change it to s.equals(u).

- It seems like for the tests, you guys have index_of confused with get. You have tests such as this: s->index_of(1)->equals("hello") (line 148) (this is in every test), when it should be s->index_of("hello") == 1

If we find anymore we'll let you know.

**Comment by saifshaikh48** [comment]
1. Changed (although our resining here was suppose `int a = 0; int b = 1;` were created, you'd still want to be able to add these into a bool array but the conversion is implicit anyway).
2. Updated the StringArray deal with String* as intended, thanks for pointing that out. Fixed that test to reflect this. (Refer to the StrList we had to make in the warmups for implementation hints)
3. Fixed all those . method calls.
4. You are correct, fixed.

**Comment by sbhornjr** [comment]
Thanks for fixing some of that stuff. Looks like there are still a couple of issues, though. 

Looks like you fixed some of the int values in the boolean array, but some are still there.

For my third point, I think you misunderstood. Using a . instead of a -> was an issue, but the other issue was the specific line of s->equal() == u->equal() (which appears multiple times) because the method is equals, not equal, and it takes in a value instead of returning one for comparison. So, the line should be s->equals(u).

As for changing the StringArray to deal with Strings*'s instead of char*'s - this is great, but the tests still do not reflect that. Instead of pushing something like "hello" to the array, you would need to do String* a = new String("hello"), and then add a to the array. The other part of this is when you have Strings in the test, you set them as String a, but they need the pointer (String* a).

**Comment by saifshaikh48** [comment]
Taking a look within the hour

**Comment by saifshaikh48** [comment]
> Taking a look within the hour

Done, let us know if anything else is needed
