### ISSUE TITLE
Some BoolArray methods expect int instead of bool

### ISSUE THREAD

**Issue by xiaju** [saifshaikh48/SwDev_A1_part2#8]
`void add(size_t i, int e); // Inserts e at i`
There are a couple of lines like this in BoolArray

Additionally, there is a test for Bool Array `t->add(0, -1)`

if add is changed, then this test becomes invalid since -1 will be cast to true.

**Comment by saifshaikh48** [comment]
then add a constraint to handle this, this is an implementation detail

**Comment by xiaju** [comment]
So it's correct that add should accept an int then? it seems strange that we wouldn't use a bool

**Comment by saifshaikh48** [comment]
I would handle it based on the tests.

**Comment by xiaju** [comment]
It seems that the API for BoolArray is inconsistent with itself though.

```
		void push_back(bool e); // Appends e to end
		void add(size_t i, int e); // Inserts e at i
```

add and push_back do essentially the same thing yet one expects a bool and the other expects an int

**Comment by saifshaikh48** [comment]
You're correct, we had made that change to push_back based on an earlier request. I'll change add() also then update the test

**Comment by xiaju** [comment]
thanks!

**Comment by saifshaikh48** [comment]
this should be fixed along with float/memory pull request, lmk if not @xiaju @arthurarmani

**Comment by xiaju** [comment]
thanks!

**Comment by xiaju** [comment]
sorry i think the tests are almost good, but 2 things
1) t/test refer to the same pointer and is deleted twice, causing a segfault
```
  s->add(0, t);
  String* test = s->remove(0);
  s->add(0, t2);
  s->push_back(t3);
  String* replaced = s->set(1, r);
  s->clear();
  t_true(test->equals(t));
  t_true(replaced->equals(t3));

  delete test;
  delete replaced;
  t_true(s->is_empty());
  t_true(s->size() == 0);

  delete s;
  delete t;
  delete t2;
  delete t3;
  delete r;
```

2) float comparisons are done using == which isn't safe due to floating point imprecision. It's causing the tests to fail on my machine. Usually you can just do something like `abs(f1 - f2) < .00001` to fix this

**Comment by saifshaikh48** [comment]
Will look at this in a bit

**Comment by saifshaikh48** [comment]
resolved
